"""set_id => osu_set_id

Revision ID: 050735018529
Revises: 1513d08eca9f
Create Date: 2019-12-16 14:55:24.727116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050735018529'
down_revision = '1513d08eca9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.alter_column('set_id', new_column_name='osu_set_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.alter_column('osu_set_id', new_column_name='set_id')

    # ### end Alembic commands ###
