"""add ok and perfect judges and makes judge default to 0

Revision ID: 1513d08eca9f
Revises: 732bdbc185d9
Create Date: 2019-12-14 05:46:37.971300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1513d08eca9f'
down_revision = '732bdbc185d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ok', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('perfect', sa.Integer(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('perfect')
        batch_op.drop_column('ok')

    # ### end Alembic commands ###
