"""osmos column

Revision ID: 2d303aab17e2
Revises: cf43cabe7ac2
Create Date: 2019-12-30 15:15:44.869363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d303aab17e2'
down_revision = 'cf43cabe7ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osmos', sa.Integer(), nullable=True))
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.VARCHAR(length=2), nullable=True))
        batch_op.drop_column('osmos')

    # ### end Alembic commands ###
