"""add difficulty details (cs, ar, sr...) and set_id

Revision ID: 732bdbc185d9
Revises: 00006ec3eb4f
Create Date: 2019-12-13 23:34:32.284678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732bdbc185d9'
down_revision = '00006ec3eb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('ar', sa.Float(), nullable=True))
    op.add_column('chart', sa.Column('cs', sa.Float(), nullable=True))
    op.add_column('chart', sa.Column('hp', sa.Float(), nullable=True))
    op.add_column('chart', sa.Column('od', sa.Float(), nullable=True))
    op.add_column('chart', sa.Column('set_id', sa.Integer(), nullable=True))
    op.add_column('chart', sa.Column('sr', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('mode', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'mode')
    op.drop_column('chart', 'sr')
    op.drop_column('chart', 'set_id')
    op.drop_column('chart', 'od')
    op.drop_column('chart', 'hp')
    op.drop_column('chart', 'cs')
    op.drop_column('chart', 'ar')
    # ### end Alembic commands ###
