"""score version

Revision ID: 93012ce9a92f
Revises: f7086c41ddc4
Create Date: 2019-12-11 22:28:49.874061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93012ce9a92f'
down_revision = 'f7086c41ddc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'version')
    # ### end Alembic commands ###
