"""playcount and osmos for players

Revision ID: c3366a1661c4
Revises: fe2f3d4ec47f
Create Date: 2019-12-30 23:07:55.536781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3366a1661c4'
down_revision = 'fe2f3d4ec47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osmos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('playcount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('playcount')
        batch_op.drop_column('osmos')

    # ### end Alembic commands ###
