"""init

Revision ID: f7086c41ddc4
Revises: 
Create Date: 2019-12-11 20:38:22.348165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7086c41ddc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_romanized', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('artist_romanized', sa.String(length=128), nullable=True),
    sa.Column('difficulty_name', sa.String(length=128), nullable=True),
    sa.Column('creator_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('osu_join_date', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('twitter', sa.String(length=32), nullable=True),
    sa.Column('discord', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('great', sa.Integer(), nullable=True),
    sa.Column('good', sa.Integer(), nullable=True),
    sa.Column('meh', sa.Integer(), nullable=True),
    sa.Column('miss', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=2), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=True),
    sa.Column('mods', sa.String(length=128), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('client', sa.String(length=128), nullable=True),
    sa.Column('chart_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('player')
    op.drop_table('chart')
    # ### end Alembic commands ###
