"""add personal_best column

Revision ID: fe2f3d4ec47f
Revises: d49fa3ae3344
Create Date: 2019-12-30 22:26:18.179526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2f3d4ec47f'
down_revision = 'd49fa3ae3344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_best', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('player_best')

    # ### end Alembic commands ###
